x = int(input('Escreva onde está o ponto [x]: '))
y = int(input('Escreva onde está o ponto [y]: '))


if x == 0 and y == 0:
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('----------------:)-----------------')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
elif x > 0 and y > 0:
    print('                 |                 ')
    print('                 |                 ')
    print('                 |        :)       ')
    print('                 |                 ')
    print('                 |                 ')
    print('-----------------|-----------------')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
elif x < 0 and y < 0:
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('-----------------|-----------------')
    print('                 |                 ')
    print('                 |                 ')
    print('      :)         |                 ')
    print('                 |                 ')
    print('                 |                 ')
elif x < 0 and y > 0:
    print('                 |                 ')
    print('                 |                 ')
    print('       :)        |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('-----------------|-----------------')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
elif x > 0 and y < 0:
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |                 ')
    print('-----------------|-----------------')
    print('                 |                 ')
    print('                 |                 ')
    print('                 |         :)      ')
    print('                 |                 ')
    print('                 |                 ')
